### ISSUE TITLE
Some of Ganon moves lacks some of feature and CPU Ganon never uses Laser Attack and Back-Slash

### ISSUE THREAD

**Issue by Minkachrgza-e** [NemesisSSBU/Playable_Bosses#22]
Since Ganon got stun state, then after that he originally can use laser attack and thunder slash is doubled but he cannot use doubled thunder slash even in player (cpu cannot use it too), and CPU Ganon never uses laser attack even after stun state (if possible it'd be great to see doubled thunder slash in both player/cpu, and cpu Ganon does laser attack)

**Comment by NemesisSSBU** [comment]
Thank you for the report and this should now be fixed on the CPU side of Ganon in the full release. On the player side of things, we want to stray away from forcing attacks (even though there is a pattern) and put those attacks in the hands of the player.

**Comment by Minkachrgza-e** [comment]
does that mean Ganon will still unable to use double thunder slash in anyway?

**Comment by NemesisSSBU** [comment]
No, he’ll get his own double thunder slash button. Thing is it’s a little bit more complicated than initially expected since it’s not actually an item status like the rest of the moves.

**Comment by NemesisSSBU** [comment]
This is issue has been fixed in the [full release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0)
